# Generated by Django 6.1 on 2026-08-31 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('course_title', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(db_index=True, max_length=20)),
                ('course_title', models.CharField(blank=True, max_length=255)),
                ('exam_date', models.CharField(blank=True, max_length=50)),
                ('exam_time', models.CharField(blank=True, max_length=50)),
                ('exam_datetime', models.DateTimeField(blank=True, null=True)),
                ('campus', models.CharField(blank=True, max_length=100)),
                ('source_url', models.TextField(blank=True)),
                ('last_scraped', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VenueAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=255)),
                ('range_start', models.CharField(blank=True, max_length=30)),
                ('range_end', models.CharField(blank=True, max_length=30)),
                ('allocation_text', models.TextField(blank=True)),
                ('timetable_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_allocations', to='timetable.timetableentry')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to='timetable.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='timetable.student')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='PersonalTimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_venue', models.CharField(blank=True, max_length=255)),
                ('exam_datetime', models.DateTimeField(blank=True, null=True)),
                ('match_confidence', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_entries', to='timetable.student')),
                ('timetable_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.timetableentry')),
            ],
            options={
                'unique_together': {('student', 'timetable_entry')},
            },
        ),
    ]
